version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306/tcp"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    build: .
    ports:
      - "${WWW_PORT}:80"
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/var/www/html

volumes:
  db_data: